modLoader="javafml"
loaderVersion="[44,)"
license="MIT License"
issueTrackerURL="https://github.com/Majrusz/MajruszsAccessories/issues"

[[mods]]
    modId="majruszsaccessories"
    version="1.1.4"
    displayName="Majrusz's Accessories"
    updateJSONURL="https://raw.githubusercontent.com/Majrusz/MinecraftCommon/main/Accessories/update.json"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/majruszs-accessories"
    logoFile="logo.png"
    credits="Thanks for all your support and downloads!"
    authors="Majrusz"
    description='''Mod that adds new special accessories to make certain aspects of the game more enjoyable.'''

[[dependencies.majruszsaccessories]]
    modId="forge"
    mandatory=true
    versionRange="[44.0.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.majruszsaccessories]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.majruszsaccessories]]
    modId="mlib"
    mandatory=true
    versionRange="[3.2.0,4.0.0)"
    ordering="NONE"
    side="BOTH"

[[dependencies.majruszsaccessories]]
    modId="curios"
    mandatory=false
    versionRange="[1.19.3-5.1.1.2,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.majruszsaccessories]]
    modId="majruszsdifficulty"
    mandatory=false
    versionRange="[1.7.0,)"
    ordering="AFTER"
    side="BOTH"